local settings = {
	nu = true,
	relativenumber = true,
	tabstop = 2,
	softtabstop = 2,
	shiftwidth = 2,
	expandtab = false,
	smartindent = true,
	wrap = true,
	textwidth = 120,
	swapfile = false,
	backup = false,
	undodir = os.getenv("HOME") .. "/.vim/undodir",
	undofile = true,
	hlsearch = false,
	incsearch = true,
	termguicolors = true,
	scrolloff = 8,
	updatetime = 50,
	colorcolumn = { "80", "120" },
	foldenable = false,
	fillchars = {
		diff = "",
		fold = " ",
		eob = " ",
		horiz = "━",
		horizup = "┻",
		horizdown = "┳",
		vert = "┃",
		vertleft = "┫",
		vertright = "┣",
		verthoriz = "╋",
		foldclose = "",
		foldopen = "",
		foldsep = " ",
	},
	autoread = true,
	cmdheight = 1,
	completeopt = { "menuone", "noselect" },
	conceallevel = 0,
	fileencoding = "utf-8",
	ignorecase = true,
	mouse = "a",
	pumheight = 10,
	showmode = false,
	showtabline = 2,
	smartcase = true,
	splitbelow = true,
	splitright = true,
	timeoutlen = 1000,
	writebackup = false,
	cursorline = true,
	number = true,
	numberwidth = 3,
	sidescrolloff = 8,
	errorbells = false,
	title = true,
	list = true,
	listchars = {
		-- eol = "↲",
		tab = "» ",
		nbsp = "␣",
		trail = "·",
		extends = "→",
		precedes = "←",
	},
	showbreak = "↪",
	spell = true,
	spelllang = { "en_us" },
	-- Figure out what these do:
	signcolumn = "yes:1",
	splitkeep = "screen",
	shortmess = "filnxtToOFWIcC",
};

for k, v in pairs(settings) do
	vim.opt[k] = v
end
