return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function () 
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"asm",
				"bash",
				"c",
				"clojure",
				"cmake",
				"comment",
				"cpp",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"ebnf",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gotmpl",
				"gowork",
				"gpg",
				"graphql",
				"haskell",
				"helm",
				"html",
				"java",
				"javascript",
				"jq",
				"json",
				-- "latex",
				"lua",
				"luadoc",
				"luap",
				"make",
				"markdown",
				"markdown_inline",
				"nix",
				"php",
				"phpdoc",
				"python",
				"regex",
				"rust",
				"scala",
				"sql",
				"ssh_config",
				-- "swift",
				"templ",
				"terraform",
				"toml",
				"tsv",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"zig",
			},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },
		})
	end
}
